#Note: fields with a '_' in it are reserved for ArcGIS Online. If the features aren't Hosted, we can remove the '_'
import numpy as np

dts = {
  "curr":np.dtype(
  [
    ('_ID', np.int),
    ('caveat', '|S1024'),
    ('classification', '|S256'),
    ('CURRENCY_SCORE'.lower(), np.int32),
    ('DOM_DATE'.lower(), '|S48'),
    ('DOM_DATE_CNT'.lower(), np.int32),
    ('DOM_DATE_PER'.lower(), np.float64),
    ('DOM_YEAR'.lower(), '|S48'),
    ('DOM_YEAR_CNT'.lower(), np.int32),
    ('DOM_YEAR_PER'.lower(), np.float64),
    ('FEATURE_CNT'.lower(), np.int32),
    ('NEWEST_DATE'.lower(), '|S1024'),
    ('NO_DATE_CNT'.lower(), np.int32),
    ('NO_DATE_PER'.lower(), np.float64),
    ('OLDEST_DATE'.lower(), '|S1024'),
    ('PCT_10_YEAR'.lower(), np.float64),
    ('PCT_15_PLUS_YEAR'.lower(), np.float64),
    ('PCT_15_YEAR'.lower(), np.float64),
    ('PCT_2_YEAR'.lower(), np.float64),
    ('PCT_5_YEAR'.lower(), np.float64)
  ]),
  "poac":np.dtype(
  [
    ('_ID', np.int),
    ('caveat', '|S1024'),
    ('classification', '|S256'),
    ('feature_cnt', np.int32),
    ('PA_MAX'.lower(), np.float64),
    ('PA_MEAN'.lower(), np.float64),
    ('PA_MEDIAN'.lower().lower(), np.float64),
    ('PA_MIN'.lower(), np.float64),
    ('PA_MODE'.lower(), np.float64),
    ('PA_NULL_CNT'.lower(), np.int32),
    ('PA_NULL_PCT'.lower(), np.float64),
    ('PA_SCORE'.lower(), np.int32),
    ('PA_TIER'.lower(), '|S1024')
  ]),
  "srln":np.dtype(
  [
    ('_ID', np.int),
    ('caveat', '|S1024'),
    ('classification', '|S256'),
    ('feature_cnt', np.int32),
    ('PRI_SOURCE'.lower(), '|S256'),
    ('PRI_SOURCE_CNT'.lower(), np.int32),
    ('PRI_SOURCE_PER'.lower(), np.float64),
    ('SEC_SOURCE'.lower(), '|S256'),
    ('SEC_SOURCE_CNT'.lower(), np.int32),
    ('SEC_SOURCE_PER'.lower(), np.float64),
    ('SOURCE_LIST'.lower(), '|S1024')
  ]),
  "logc":np.dtype(
  [
    ('_ID', np.int),
    ('caveat', '|S1024'),
    ('classification', '|S256'),
    ('feature_cnt', np.int32),
    ('LC_SCORE'.lower(), np.int32),
    ('MAX_DEF_CNT'.lower(), np.int32),
    ('MEAN_DEF_CNT'.lower(), np.float64),
    ('MEDIAN_DEF_CNT'.lower(), np.int32),
    ('MIN_DEF_CNT'.lower(), np.int32),
    ('PER_PRI'.lower(), np.float64),
    ('PER_SEC'.lower(), np.float64),
    ("PRI_ATTR_DEF".lower(), '|S20'),  # pri_attr
    ('PRI_ATTR_DEF_CNT'.lower(), np.float64),
    ('PRI_ATTR_DEF_PER'.lower(), np.float64),
    ('PRI_NUM_DEF'.lower(), np.int32),
    ('PRI_NUM_DEF_CNT'.lower(), np.int32),
    ('SEC_ATTR_DEF'.lower(), '|S20'),
    ('SEC_ATTR_DEF_CNT'.lower(), np.float64),
    ('SEC_ATTR_DEF_PER'.lower(), np.float64),
    ('SEC_NUM_DEF'.lower(), np.int32),
    ('SEC_NUM_DEF_CNT'.lower(), np.int32)
  ]),
  "cmpl":np.dtype(
  [
    ('_ID', np.int),
    ('caveat', '|S1024'),
    ('classification', '|S256'),
    ('feature_cnt', np.int32),
    ('TDS_DENSITY'.lower(), np.float64),
    ('COMP_DENSITY'.lower(), np.float64),
    ('COMPLETENESS_VALUE'.lower(), np.float64),
    ('DIFFERENCE'.lower(), np.float64)
  ]),
  "them":np.dtype(
  [
    ('_ID', np.int),
    ('caveat', '|S1024'),
    ('classification', '|S256'),
    ('COUNT_100000'.lower(), np.int32),
    ('COUNT_1000000'.lower(), np.int32),
    ('COUNT_12500'.lower(), np.int32),
    ('COUNT_2500'.lower(), np.int32),
    ('COUNT_25000'.lower(), np.int32),
    ('COUNT_250000'.lower(), np.int32),
    ('COUNT_5000'.lower(), np.int32),
    ('COUNT_50000'.lower(), np.int32),
    ('COUNT_500000'.lower(), np.int32),
    ('DOM_COUNT'.lower(), np.int32),
    ('DOM_PER'.lower(), np.float64),
    ('DOM_SCALE'.lower(), np.float64),
    ('feature_cnt', np.int32),
    ('MAX_PER'.lower(), np.float64),
    ('MAX_SCALE'.lower(), np.float64),
    ('MAX_SCALE_COUNT'.lower(), np.float64),
    ('MIN_PER'.lower(), np.float64),
    ('MIN_SCALE'.lower(), np.float64),
    ('MIN_SCALE_COUNT'.lower(), np.float64),
    ('MISSION_PLANNING'.lower(), '|S1024'),
    ('PER_100000'.lower(), np.float64),
    ('PER_1000000'.lower(), np.float64),
    ('PER_12500'.lower(), np.float64),
    ('PER_2500'.lower(), np.float64),
    ('PER_25000'.lower(), np.float64),
    ('PER_250000'.lower(), np.float64),
    ('PER_5000'.lower(), np.float64),
    ('PER_50000'.lower(), np.float64),
    ('PER_500000'.lower(), np.float64),
    ('THEM_MEAN'.lower(), np.float64)
  ])
}

field_schema = {
  "poac": [
    "PA_MEAN".lower(),
    "PA_MEDIAN".lower(),
    "PA_MODE".lower(),
    "PA_MIN".lower(),
    "PA_MAX".lower(),
    "NO_DATE_CNT".lower(),
    "NO_DATE_PCT".lower(),
    "FEATURE_CNT".lower(),
    "PA_SCORE".lower(),
    "TIER".lower()
  ],
  "cmpl": [
    'TDS_DENSITY'.lower(),
    'COMP_DENSITY'.lower(),
    'COMPLETENESS_VALUE'.lower(),
    'DIFFERENCE'.lower()
  ],
  "them": [
    'DOM_SCALE'.lower(),
    'DOM_COUNT'.lower(),
    'DOM_PER'.lower(),
    'MIN_SCALE'.lower(),
    'MIN_PER'.lower(),
    'MAX_SCALE'.lower(),
    'MAX_PER'.lower(),
    'CNT_2500'.lower(),
    'CNT_5000'.lower(),
    'CNT_12500'.lower(),
    'CNT_25000'.lower(),
    'CNT_50000'.lower(),
    'CNT_100000'.lower(),
    'CNT_250000'.lower(),
    'CNT_500000'.lower(),
    'CNT_1000000'.lower(),
    'PER_2500'.lower(),
    'PER_5000'.lower(),
    'PER_12500'.lower(),
    'PER_25000'.lower(),
    'PER_50000'.lower(),
    'PER_100000'.lower(),
    'PER_250000'.lower(),
    'PER_500000'.lower(),
    'PER_1000000'.lower(),
    'THEM_COUNT'.lower(),  # Add Underscore if AGOL
    'MISSION_PLANNING'.lower(),
    'POPULATION_SCALE'.lower(),
    'THEM_ACC_SCORE'.lower(),
    'THEM_MEAN'.lower()
  ],
  "srln": [
    'SOURCE_LIST'.lower(),
    'PRI_SOURCE'.lower(),
    'PRI_SOURCE_CNT'.lower(),
    'PRI_SOURCE_PER'.lower(),
    'SEC_SOURCE'.lower(),
    'SEC_SOURCE_CNT'.lower(),
    'SEC_SOURCE_PER'.lower()
  ],
  "curr": [
    'DOM_DATE'.lower(),
    'DOM_DATE_CNT'.lower(),
    'DOM_DATE_PER'.lower(),
    'DOM_YEAR'.lower(),
    'DOM_YEAR_CNT'.lower(),
    'DOM_YEAR_PER'.lower(),
    'OLDEST_DATE'.lower(),
    'NEWEST_DATE'.lower(),
    'NO_DATE_CNT'.lower(),
    'NO_DATE_PER'.lower(),
    'PCT_2_YEAR'.lower(),
    'PCT_5_YEAR'.lower(),
    'PCT_10_YEAR'.lower(),
    'PCT_15_YEAR'.lower(),
    'PCT_15_PLUS_YEAR'.lower(),
    'FEATURE_CNT'.lower(),
    'CURRENCY_SCORE'.lower()
  ],
  "temp_acc": [
    #'join_count',
    #'target_fid',
    'DOM_DATE'.lower(),
    'DOM_DATE_CNT'.lower(),
    'DOM_DATE_PER'.lower(),
    'DOM_YEAR'.lower(),
    'DOM_YEAR_CNT'.lower(),
    'DOM_YEAR_PER'.lower(),
    'OLDEST_DATE'.lower(),
    'NEWEST_DATE'.lower(),
    'NO_DATE_CNT'.lower(),
    'NO_DATE_PER'.lower(),
    'PCT_2_YEAR'.lower(),
    'PCT_5_YEAR'.lower(),
    'PCT_10_YEAR'.lower(),
    'PCT_15_YEAR'.lower(),
    'PCT_15_PLUS_YEAR'.lower(),
    'FEATURE_CNT'.lower(),
    'CURRENCY_SCORE'.lower(),
    'y1998',
    'y1999',
    'y2000',
    'y2001',
    'y2002',
    'y2003',
    'y2004',
    'y2005',
    'y2006',
    'y2007',
    'y2008',
    'y2009',
    'y2010',
    'y2011',
    'y2012',
    'y2013',
    'y2014',
    #'prc',
    #'orig_fid',
    'cd_since_dom_year',
    'temp_acc_score',
  ],
  "logc": [
    'MEAN_DEF_CNT'.lower(),
    'MEDIAN_DEF_CNT'.lower(),
    'MIN_DEF_CNT'.lower(),
    'MAX_DEF_CNT'.lower(),
    'PRI_NUM_DEF'.lower(),
    'SEC_NUM_DEF'.lower(),
    'PER_PRI'.lower(),
    'PER_SEC'.lower(),
    'PRI_ATTR_DEF'.lower(),
    'SEC_ATTR_DEF'.lower(),
    'PRI_ATTR_DEF_PER'.lower(),
    'SEC_ATTR_DEF_PER'.lower(),
    'FEATURE_CNT'.lower(),
    'PRI_ATTR_DEF_CNT'.lower(),
    'SEC_ATTR_DEF_CNT'.lower(),
    'LC_SCORE'.lower()
  ]
}
